export const REGISTRATION_USER = 'REGISTRATION_USER';

export const GET_QUESTIONS = 'GET_QUESTIONS';
export const COMMIT_ANSWER = 'COMMIT_ANSWER';
export const GET_RESULTS = 'GET_RESULTS';
export const END_QUIZ = 'END_QUIZ';
export const COMMIT_TENDER = 'COMMIT_TENDER';
