export const GET_PHOTO_REQUEST = 'GET_PHOTO_REQUEST';
export const GET_PHOTO_SUCCESS = 'GET_PHOTO_SUCCESS';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const COMMIT_ANSWER = 'COMMIT_ANSWER';
export const GET_RESULTS = 'GET_RESULTS';
export const END_QUIZ = 'END_QUIZ';
